config/routes.rb
Motm::Application.routes.draw do
  resources :mixes

  match 'facebook' => 'facebook#index', :as => 'facebook'

  authenticated :user do
    root :to => 'facebook#index'
  end
  root :to => "facebook#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    else
        can :read, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/mix.rb
class Mix < ActiveRecord::Base
  attr_accessible :author, :image, :title, :url

  validates_presence_of :url
  validates :url, :format => URI::regexp(%w(http https))
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/facebook_controller.rb
class FacebookController < ApplicationController

  def index
    @mixes = Mix.all
    @mix = Mix.new

    respond_to do |format|
      format.html 
      format.json { render json: @mixes }
    end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/mixes_controller.rb
class MixesController < ApplicationController
  include MixesHelper

  load_and_authorize_resource
  before_filter :check_mix_exists_already, :only => [:create]

  # GET /mixes
  # GET /mixes.json
  def index
    @mixes = Mix.all
    @mix = Mix.new

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @mixes }
    end
  end

  # GET /mixes/1
  # GET /mixes/1.json
  def show
    @mix = Mix.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/new
  # GET /mixes/new.json
  def new
    @mix = Mix.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @mix }
    end
  end

  # GET /mixes/1/edit
  def edit
    @mix = Mix.find(params[:id])
  end

  # POST /mixes
  # POST /mixes.json
  def create

    @mix = Mix.new
    if params[:mix]
    @mix.url = params[:mix][:url]
     embedly(@mix.url)
    end    
   

    respond_to do |format|
      if @mix.save
        format.html { redirect_to @mix, notice: 'Mix was successfully created.' }
        format.json { render json: @mix, status: :created, location: @mix }
      else
        format.html { render action: "new" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /mixes/1
  # PUT /mixes/1.json
  def update
    @mix = Mix.find(params[:id])

    respond_to do |format|
      if @mix.update_attributes(params[:mix])
        format.html { redirect_to @mix, notice: 'Mix was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @mix.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mixes/1
  # DELETE /mixes/1.json
  def destroy
    @mix = Mix.find(params[:id])
    @mix.destroy

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  private
        def check_mix_exists_already
            @mix = User.find(params[:mix])
        end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mixes_helper.rb
module MixesHelper
	require 'embedly'
	require 'json'


  def embedly(url)

    embedly_api = Embedly::API.new :key => 'd30e91b2207a40469be014c739c2ddb3', :user_agent => 'Mozilla/5.0 (compatible; mytestapp/1.0; my@email.com)'
    obj = embedly_api.oembed :url => url
    @mix.image =  obj[0].thumbnail_url
    @mix.title = obj[0].title
    @mix.author = obj[0].author_name

  end

end

app/views/facebook/index.html.erb
<h1>Mix of the Month</h1>

<br />
<%#= link_to 'New Mix', new_mix_path %>

<section class="mix-form well">
<%= render 'mixes/form' %>
</section>


<br />



<% @mixes.each do |mix| %>

    <h2><%= link_to mix.title, mix  %> <br/> <small>via <%= mix.author %></small></h2>
      <%= image_tag mix.image, :width => "100px" %>

      <hr/>

   <p>
   	<% if current_user.present? && current_user.has_role?('admin') %>
    <%= link_to 'Show', mix %> | <%= link_to 'Edit', edit_mix_path(mix) %> | <%= link_to 'Destroy', mix, method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </p>
<% end %>

app/views/home/index.html.erb
<h3>Dashboard</h3>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 2.3 %>
<div class="navbar navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'MotM', root_path %><li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Motm" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Motm" %>">
    <%= stylesheet_link_tag "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <script src="http://cdn.embed.ly/jquery.embedly-3.1.1.min.js" type="text/javascript"></script>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>

    <script type="text/javascript">

      $('a').embedly({key: 'd30e91b2207a40469be014c739c2ddb3'});


    </script>
  </body>
</html>

app/views/mixes/_form.html.erb
<%= simple_form_for(@mix) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title, as: :hidden %>
    <%= f.input :author, as: :hidden %>
    <%= f.input :image, as: :hidden %>
    <%= f.input :url, hint: 'Enter a link to your mix of the month...', :label => false, :placeholder => 'e.g. http://i.mixcloud.com/CCaDWK' %>
  </div>


    <%= f.button :submit, :value => "Add Mix" %>

<% end %>

app/views/mixes/edit.html.erb
<h1>Editing mix</h1>

<%= render 'form' %>

<%= link_to 'Show', @mix %> |
<%= link_to 'Back', mixes_path %>

app/views/mixes/index.html.erb
<%#= link_to 'New Mix', new_mix_path %>

<section class="mix-form well">
<%= render 'mixes/form' %>
</section>


<br />

<h1>Mixes of the Month</h1>

<hr />

<% @mixes.each do |mix| %>

    <h2><%= link_to mix.title, mix  %> <br/> <small>via <%= mix.author %></small></h2>
      <%= image_tag mix.image, :width => "100px" %>

      <hr/>

    <p>
    <%= link_to 'Show', mix %> | <%= link_to 'Edit', edit_mix_path(mix) %> | <%= link_to 'Destroy', mix, method: :delete, data: { confirm: 'Are you sure?' } %>
  </p>
<% end %>

app/views/mixes/new.html.erb
<h1>New mix</h1>

<%= render 'form' %>

<%= link_to 'Back', mixes_path %>

app/views/mixes/show.html.erb
<h1>
	<p class="pull-left">
  <%= image_tag @mix.image, :width => "100px" %>
</p>
  <%= @mix.title %>
 <br/>
  <small>via <%= @mix.author %></small>
</h1>

<br/>

<section>
  <%= link_to "#{@mix.url}", @mix.url %>
</section>

<br/>

<% if current_user.present? && current_user.has_role?('admin') %>
<%= link_to 'Edit', edit_mix_path(@mix) %>
<% end %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Registered</th>
      <th>Role</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= link_to user.name, user %></td>
      <td><%= user.email %></td>
      <td><%= user.created_at.to_date %></td>
      <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
      <td>
        <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
        <%= render user %>
      </td>
      <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>